plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"
    - "sandbox/**/*"
    - "app/**/*"

# Sorbet sigs inflate line counts significantly
Metrics/MethodLength:
  CountAsOne:
    - heredoc
  Max: 40
  Exclude:
    - "lib/hakumi_orm/sql_compiler.rb"

Metrics/AbcSize:
  Max: 30
  Exclude:
    - "lib/hakumi_orm/sql_compiler.rb"
    - "lib/hakumi_orm/codegen/generator.rb"
    - "lib/hakumi_orm/codegen/generator_options.rb"
    - "lib/hakumi_orm/relation.rb"
    - "lib/hakumi_orm/configuration.rb"

Metrics/ClassLength:
  Max: 380
  CountAsOne:
    - heredoc
  Exclude:
    - "test/**/*"

Metrics/ModuleLength:
  Max: 220

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "*.gemspec"
    - "lib/hakumi_orm/tasks.rb"

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Metrics/ParameterLists:
  Max: 5
  Exclude:
    - "lib/hakumi_orm/sql_compiler.rb"
    - "lib/hakumi_orm/sql_compiler_expr.rb"
    - "lib/hakumi_orm/migration.rb"
    - "lib/hakumi_orm/migration/table_definition.rb"
    - "lib/hakumi_orm/migration/sql_generator.rb"
    - "lib/hakumi_orm/migration/column_definition.rb"
    - "lib/hakumi_orm/codegen/association_builder.rb"
    - "lib/hakumi_orm/codegen/column_info.rb"
    - "lib/hakumi_orm/codegen/custom_association.rb"
    - "lib/hakumi_orm/codegen/generator_options.rb"
    - "lib/hakumi_orm/codegen/model_annotator.rb"
    - "lib/hakumi_orm/database_config.rb"
    - "test/**/*"

Metrics/CollectionLiteralLength:
  Enabled: false

# Performance ORM uses short variable names intentionally (i, n, buf, idx)
Naming/MethodParameterName:
  AllowedNames:
    - i
    - n
    - e
    - v
    - j
    - a
    - b
    - ci
    - ri
    - op
    - pk
    - fk
    - id
    - qn

Naming/MethodName:
  ForbiddenPatterns:
    - !ruby/regexp /\Amethod_missing\z/
    - !ruby/regexp /\Arespond_to_missing\?\z/

# Sorbet requires named block params in sigs; anonymous forwarding is incompatible
Naming/BlockForwarding:
  EnforcedStyle: explicit

# is_null / is_not_null are SQL semantics, not Ruby predicates
Naming/PredicatePrefix:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

# Sorbet abstract classes don't always call super
Lint/MissingSuper:
  Enabled: false

Style/Documentation:
  Enabled: true
  Include:
    - "lib/**/*.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Sorbet/ForbidTStruct:
  Enabled: true

# All blk.call sites receive the block via forwarding (&blk) or store it as a Proc.
# The Proc is already allocated before blk.call, so yield saves nothing.
# connector.call / @connector.call are stored Procs (not blocks), which yield can't replace.
Performance/RedundantBlockCall:
  Enabled: false

Style/Send:
  Enabled: true
  Exclude:
    - "test/**/*"

Performance/OpenStruct:
  Enabled: true

Style/TopLevelMethodDefinition:
  Enabled: true

Layout/LineLength:
  Max: 140
  Exclude:
    - "test/**/*"
