module HakumiORM
  module Adapter
    class Result
      def row_count: () -> Integer
      def get_value: (Integer row, Integer col) -> String?
      def fetch_value: (Integer row, Integer col) -> String
      def values: () -> Array[Array[String?]]
      def column_values: (Integer col) -> Array[String?]
      def affected_rows: () -> Integer
      def close: () -> void
    end

    class Base
      def dialect: () -> Dialect::Base
      def exec_params: (String sql, Array[pg_value] params) -> Result
      def exec: (String sql) -> Result
      def close: () -> void
      def transaction: () { (Base adapter) -> void } -> void
    end
  end
end
