module HakumiORM
  class Expr
    def and: (Expr other) -> AndExpr
    def or: (Expr other) -> OrExpr
    def not: () -> NotExpr
  end

  class Predicate < Expr
    attr_reader field: FieldRef
    attr_reader op: Symbol
    attr_reader binds: Array[Bind]

    def initialize: (FieldRef field, Symbol op, Array[Bind] binds) -> void
  end

  class AndExpr < Expr
    attr_reader left: Expr
    attr_reader right: Expr

    def initialize: (Expr left, Expr right) -> void
  end

  class OrExpr < Expr
    attr_reader left: Expr
    attr_reader right: Expr

    def initialize: (Expr left, Expr right) -> void
  end

  class NotExpr < Expr
    attr_reader inner: Expr

    def initialize: (Expr inner) -> void
  end
end
