module HakumiORM
  module Adapter
    class PostgresqlResult < Result
      def initialize: (untyped pg_result) -> void
    end

    class Postgresql < Base
      attr_reader dialect: Dialect::Postgresql

      def initialize: (untyped pg_conn) -> void
      def self.connect: (Hash[Symbol, String | Integer] params) -> Postgresql
      def exec_params: (String sql, Array[pg_value] params) -> PostgresqlResult
      def exec: (String sql) -> PostgresqlResult
      def close: () -> void
    end
  end
end
