module HakumiORM
  module Codegen
    class ColumnInfo
      attr_reader name: String
      attr_reader data_type: String
      attr_reader udt_name: String
      attr_reader nullable: bool
      attr_reader default: String?
      attr_reader max_length: Integer?
    end

    class ForeignKeyInfo
      attr_reader column_name: String
      attr_reader foreign_table: String
      attr_reader foreign_column: String
    end

    class TableInfo
      attr_reader name: String
      attr_reader columns: Array[ColumnInfo]
      attr_reader foreign_keys: Array[ForeignKeyInfo]
      attr_accessor primary_key: String?

      def initialize: (String name) -> void
    end

    class SchemaReader
      PG_TABLES_SQL: String
      PG_COLUMNS_SQL: String
      PG_PRIMARY_KEYS_SQL: String
      PG_FOREIGN_KEYS_SQL: String

      def initialize: (Adapter::Base adapter) -> void
      def read_tables: (?schema: String) -> Hash[String, TableInfo]

      private

      def read_table_names: (String schema, Hash[String, TableInfo] tables) -> void
      def read_columns: (String schema, Hash[String, TableInfo] tables) -> void
      def read_primary_keys: (String schema, Hash[String, TableInfo] tables) -> void
      def read_foreign_keys: (String schema, Hash[String, TableInfo] tables) -> void
    end
  end
end
