module HakumiORM
  module Codegen
    module TypeMap
      DIALECT_MAPS: Hash[Symbol, Hash[String, HakumiType]]

      def self.hakumi_type: (Symbol dialect, String data_type, ?String? udt_name) -> HakumiType
      def self.cast_expression: (HakumiType hakumi_type, String raw_expr, nullable: bool) -> String
    end
  end
end
